create table if not exists foiarchive.topics (
    corpus          corpus_t,
    topic_id        integer,
    title           text         not null,
    name            text,
    primary key (corpus, topic_id)
);
grant select on foiarchive.topics to web_anon;
comment on table foiarchive.topics is
    'Set of topics generated by topic modeling';


create table if not exists foiarchive.topic_docs (
    corpus          corpus_t,
    topic_id        integer,
    doc_id          id_d,
    score           float       not null,
    primary key (corpus, topic_id, doc_id)
);
grant select on foiarchive.topics_docs to web_anon;
comment on table topic_docs is
   'Strength of assocation between a topic and a doc';

-- after running load
alter table topic_docs add foreign key (corpus, topic_id) references topics(corpus, topic_id);
create index on topic_docs (doc_id); 
alter table topic_docs add foreign key (doc_id) references docs(doc_id);
